language: clojure
sudo: false
lein: lein
script: lein do clean, javac, test
jdk:
  - openjdk9
  - oraclejdk9
  - openjdk11
branches:
  except:
    - gh-pages
# cache:
#   directories:
#   - $HOME/.m2
